version: '3'

services:
  portainer:
    image: portainer/portainer
    ports:
      - 9100:9000
    command: -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./portainer/data:/data
    restart: unless-stopped

  influxdb:
    build: influxdb
    environment: 
      - INFLUXDB_DB=db0
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=supersecretpassword
      - INFLUXDB_USER=user
      - INFLUXDB_USER_PASSWORD=secretpassword
      - PRE_CREATE_DB:livelab-sensors
    ports: 
      - 8186:8086
    volumes: 
      - ./influxdb/data:/var/lib/influxdb
    restart: unless-stopped

  mosquitto:
    build: mosquitto
    ports: 
      - 1183:1883
    volumes: 
      - ./mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/data/etc/mosquitto:/etc/mosquitto:ro
      - ./mosquitto/data/var/log/mosquitto:/var/log/mosquitto:rw

    depends_on: 
      - influxdb
    restart: unless-stopped
  
  grafana:
    build: grafana
    ports: 
      - 3100:3000
    environment: 
      - GF_SECURITY_ADMIN_PASSWORD=secret
    user: "1000"
    volumes:
      - ./grafana/data:/var/lib/grafana
    restart: unless-stopped

  nodered:
    build: nodered
    ports:
      - 1180:1880
    depends_on: 
      - mosquitto
      - influxdb
    user: root:root
    command: -H /var/run/dbus/system_bus_socket
    environment:
      - FLOWS=flows.json
    volumes:
      - ./nodered/data:/data
      - ./nodered/data/tmp:~/.node-red
    restart: unless-stopped
